// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileFieldNames          = builder.RawFieldNames(&File{})
	fileRows                = strings.Join(fileFieldNames, ",")
	fileRowsExpectAutoSet   = strings.Join(stringx.Remove(fileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileRowsWithPlaceHolder = strings.Join(stringx.Remove(fileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileModel interface {
		Insert(ctx context.Context, data *File) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*File, error)
		FindOneByHash(ctx context.Context, hash string) (*File, error)
		Update(ctx context.Context, data *File) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFileModel struct {
		conn  sqlx.SqlConn
		table string
	}

	File struct {
		Id        int64     `db:"id"`
		CreateAt  time.Time `db:"create_at"`
		UpdateAt  time.Time `db:"update_at"`
		DeleteAt  time.Time `db:"delete_at"`
		Name      string    `db:"name"`
		Ext       string    `db:"ext"`
		Size      int64     `db:"size"`
		Hash      string    `db:"hash"`
		LoaclPath string    `db:"loacl_path"`
		Status    string    `db:"status"`
	}
)

func newFileModel(conn sqlx.SqlConn) *defaultFileModel {
	return &defaultFileModel{
		conn:  conn,
		table: "`file`",
	}
}

func (m *defaultFileModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFileModel) FindOne(ctx context.Context, id int64) (*File, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileRows, m.table)
	var resp File
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileModel) FindOneByHash(ctx context.Context, hash string) (*File, error) {
	var resp File
	query := fmt.Sprintf("select %s from %s where `hash` = ? limit 1", fileRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, hash)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileModel) Insert(ctx context.Context, data *File) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, fileRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeleteAt, data.Name, data.Ext, data.Size, data.Hash, data.LoaclPath, data.Status)
	return ret, err
}

func (m *defaultFileModel) Update(ctx context.Context, newData *File) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.DeleteAt, newData.Name, newData.Ext, newData.Size, newData.Hash, newData.LoaclPath, newData.Status, newData.Id)
	return err
}

func (m *defaultFileModel) tableName() string {
	return m.table
}
